var authors = ["Vincent Van Gogh",
    "Salvador Dali",
    "Rene Magritte",
    "Rembrant Harmenszoon van Rijn",
    "Raphael",
    "Peter Paul Rubens",
    "Paul Cezanne",
    "Pablo Picasso",
    "Michelangelo Buonarroti",
    "Mark Rothko",
    "Leonardo da Vinci",
    "Johannes Vermeer",
    "Jean-Honoré Fragonard",
    "James Abbott McNei",
    "Henri Matisse",
    "Gustav Klimt",
    "Grant Wood",
    "Georges Seurat",
    "Edvard Munch",
    "Diego Velazquez",
    "Diego Rivera",
    "Claude Monet",
    "Allaert van Everdingen"]
