var paintings = ["Self-portrait",
    "starrynight",
    "Metamorphosis of Narcissus",
    "Sleep",
    "Swans Reflecting Elephants",
    "The Persistence of Memory",
    "The Temptation of Saint Anthony",
    "The Son of Man",
    "Pope Leo X ",
    "The School of Athens",
    "Massacre of the Innocents",
    "Pyramid of skulls",
    "The Card Players",
    "Persian Sibyl ",
    "The Creation of Adam",
    "The last judgment",
    "Royal Red and Blue",
    "Gioconda",
    "Lady with an Ermine",
    "Salvator Mundi",
    "Self-portrait in red chalk",
    "Girl with a Pearl Earring",
    "The Kitchen Maid Milkmaid",
    "A Young Woman Seated with a Dog and a Watering Can in a Garden",
    "The Bathers",
    "The Reader",
    "The Stolen Kiss",
    "Golden Tears",
    "The Kiss",
    "The Lady in Gold(Portrait of Adele Bloch-Bauer I)",
    "Water Serpents",
    "Fauvism and Goldfish",
    "The Cat With Red Fish",
    "The Dance",
    "American Gothic",
    "A Sunday Afternoon on the Island of La Grande Jatte",
    "Las Meninas",
    "The Flower Carrier",
    "houses of parliament ",
    "Impression Sunrise",
    "Sunflowers ",
    "The Woman with a Parasol",
    "Fishing Boats In A Harbor"]





// sed 's/\(.*\)/"\1"/g' paintings.txt >> paintingstxt
// sed 's/\(.*\)/"\1"/g' paintings.txt >> paintingstxt
